### ISSUE TITLE
[存储设置]原始数据设置，启用原始数据的设备，设置设备保存不成功

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/nflow#11]
[存储设置]原始数据设置，启用原始数据的设备，设置设备保存不成功

![image](https://user-images.githubusercontent.com/22296563/30267112-14730890-9714-11e7-895c-6fb9995deaa2.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by xiauye** [comment]
已确认
