### ISSUE TITLE
[修改hengweiURL]把hengweiURL修改回来也报错，基本功能上都报错

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/nflow#2]
[主要功能]把URL修改回来也报错，基本功能上都报错
![image](https://user-images.githubusercontent.com/22296563/30193940-d40119e8-9482-11e7-9934-b9ef12223726.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by xiauye** [comment]
ok
