### ISSUE TITLE
[保留数据设置7天]把系统数据向后推一个月，报错。data/nflow下面数据也没有删除

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/nflow#9]
[保留数据设置7天]把系统数据向后推一个月，报错。data/nflow下面数据也没有删除
![image](https://user-images.githubusercontent.com/22296563/30261610-1146c530-9700-11e7-93dc-43c3eb8a22b8.png)

**Comment by hengwei-lhm** [comment]
页面修改后 app.properties 的内容能被修改

**Comment by xiauye** [comment]
没有报错。  数据都删除了，但是文件名称都没有删除
![image](https://user-images.githubusercontent.com/22296563/30845257-2ec475dc-a2c5-11e7-8c91-5d52dfce3c8d.png)

**Comment by runner-mei** [comment]
fixed

**Comment by xiauye** [comment]
已确认
